# How does this get run?  See https://pre-commit.com
# $ brew install pre-commit
# Then, in this directory:
# $ pre-commit install

repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.45.1
    hooks:
      - id: swiftlint
        args: [--strict]
